version: "3.7"
services:
  mysql:
    restart: always
    network_mode: bridge
    container_name: mysql
    hostname: mysql
    image: mysql:5.6.10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
