version: "3.7"
services:
  nexus:
    restart: always
    network_mode: bridge
    container_name: nexus
    hostname: nexus
    image: sonatype/nexus3:3.14.0
    ports:
      - 10600:8081
    volumes:
      - /home/nexus/nexus-data:/nexus-data
